name: "test"

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main, develop, holochain-0.1, holochain-0.2 ]
  pull_request:
    branches: [ main, develop, holochain-0.1, holochain-0.2 ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extend space
        uses: ./.github/actions/extend-space
 
      - name: Install nix
        uses: cachix/install-nix-action@v23
        with:
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
          extra_nix_config: |
            experimental-features = flakes nix-command

      - uses: cachix/cachix-action@v12
        with:
          name: holochain-ci

      - name: Build and test
        run: |
          cd $GITHUB_WORKSPACE
          nix develop --override-input "versions/scaffolding" . .#ci --command ./run_test.sh
