name: "test"

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ develop, develop-0.1, develop-0.2 ]
  pull_request:
    branches: [ develop, develop-0.1, develop-0.2 ]

jobs:
  test_fmt_lint:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: go toolchain
        uses: actions/setup-go@v5
        with:
          go-version: '=1.20.0'

      - uses: dtolnay/rust-toolchain@stable

      - name: Unittests
        run: cargo test --no-fail-fast

      - name: Format Rust
        run: cargo fmt --all --check

      - name : Lint Rust
        run: cargo clippy --all-targets -- -D warnings
#
#  testbuild:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        template: [ svelte, vue, lit, react, vanilla ]
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Extend space
#        uses: ./.github/actions/extend-space
#
#      - name: Install nix
#        uses: cachix/install-nix-action@v25
#        with:
#          install_url: https://releases.nixos.org/nix/nix-2.20.0/install
#          extra_nix_config: |
#            experimental-features = flakes nix-command
#
#      - uses: cachix/cachix-action@v14
#        with:
#          name: holochain-ci
#
#      - name: Build and test
#        run: |
#          cd $GITHUB_WORKSPACE
#          nix develop --override-input "versions/scaffolding" . .#ci --command ./run_test.sh -t ${{ matrix.template }}
#
#  testbuild_by_scope:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        scope:
#          - hello_world
#          - holo_integration
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Extend space
#        uses: ./.github/actions/extend-space
#
#      - name: Install nix
#        uses: cachix/install-nix-action@v25
#        with:
#          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
#          extra_nix_config: |
#            experimental-features = flakes nix-command
#
#      - uses: cachix/cachix-action@v14
#        with:
#          name: holochain-ci
#
#      - name: Build and test
#        run: |
#          cd $GITHUB_WORKSPACE
#          nix develop --override-input "versions/scaffolding" . .#ci --command ./run_test.sh -s ${{ matrix.scope }}
